name: onde_dev

configs:
  lavalink_config:
    file: ./lavalink/application.yml

services:
  lavalink:
    extends:
      file: docker-compose.yml
      service: lavalink
    container_name: lavalink_dev
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./lavalink/application.yml
    #       target: /opt/Lavalink/application.yml
    networks:
      - lavalink
    expose:
      - 2333

  server:
    extends:
      file: docker-compose.yml
      service: server
    container_name: server_dev
    build:
      target: dev
    secrets:
      - source: discord_bot_token
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: discord_dev_guild_id
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: lavalink_host
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: lavalink_port
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: lavalink_password
        uid: '1000'
        gid: '1000'
        mode: 0440
    develop:
      watch:
        - action: sync
          path: ./packages/server/src
          target: /app/src
        - action: rebuild
          path: ./packages/server/src/package.json
    networks:
      - lavalink

secrets:
  discord_bot_token:
    environment: DISCORD_BOT_TOKEN
  discord_dev_guild_id:
    environment: DISCORD_DEV_GUILD_ID
  lavalink_host:
    environment: LAVALINK_HOST
  lavalink_port:
    environment: LAVALINK_PORT
  lavalink_password:
    environment: LAVALINK_PASSWORD

networks:
  # create a lavalink network you can add other containers to, to give them access to Lavalink
  lavalink:
    name: lavalink