name: onde

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    build:
      context: ./lavalink
    container_name: lavalink
    profiles:
      - default
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx1G
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      - 2333

  server:
    container_name: server
    profiles:
      - default
    restart: unless-stopped
    depends_on:
      - lavalink
    build:
      context: packages/server
      target: prod
    secrets:
      - source: discord_bot_token
        mode: 0440
      - source: discord_dev_guild_id
        mode: 0440
    networks:
      - lavalink

secrets:
  discord_bot_token:
    environment: DISCORD_BOT_TOKEN
  discord_dev_guild_id:
    environment: DISCORD_DEV_GUILD_ID

networks:
  lavalink:
    name: lavalink
